export enum NotificationType {
	FOLLOW = 'FOLLOW',
	LIKE = 'LIKE',
	COMMENT = 'COMMENT',
	BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
	BOOKING_CANCELLED = 'BOOKING_CANCELLED',
	NEW_POST = 'NEW_POST',
	DISCOUNT = 'DISCOUNT',
	FREE_SLOT = 'FREE_SLOT',
	NEW_REVIEW = 'NEW_REVIEW',
}

export enum NotificationStatus {
	WAIT = 'WAIT',
	READ = 'READ',
}

export enum NotificationGroup {
	MEMBER = 'MEMBER',
	SALON = 'SALON',
	SERVICE = 'SERVICE',
	BOOKING = 'BOOKING',
	ARTICLE = 'ARTICLE',
}
